Feat/Add Travis CI
shnider/yard-frontend pull request #10
Opened 2017-07-04 21:02 UTC by shnider

Эта ветка от feat/flow-types

2017-07-04 21:34 UTC, evgenyrodionov commented on package.json
> +    "alias": "yard-shinder"
оно не заработает само по себе, надо команду вызвать же

2017-07-05 17:52 UTC, imevro requested changes

2017-07-05 17:52 UTC, evgenyrodionov commented on package.json
> +    "deploy": "yarn build && now build --public --token $NOW_TOKEN && now -alias --token $NOW_TOKEN"
что такое -alias?

2017-07-05 21:16 UTC, imevro approved these changes

2017-07-05 21:16 UTC, merged