Feat/Add modal gallery
shnider/yard-frontend pull request #12
Opened 2017-07-13 20:26 UTC by shnider

https://build-nqkxpzaala.now.sh/ 
Пока без управлениям стрелочками - не разобрался еще, как хендлить клавиши

2017-07-13 21:22 UTC, evgenyrodionov commented
addEventListener

2017-07-13 21:28 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28188575-4c98fb16-682b-11e7-803b-81f5ee9564ab.png)

2017-07-13 21:33 UTC, evgenyrodionov commented
Но в целом классно

2017-07-13 21:34 UTC, evgenyrodionov commented
а, и да, не высветляй пикчи по-умолчанию (и не затемняй никогда в жизни), это некрасиво и тупо

2017-07-19 21:13 UTC, shnider commented
https://build-lxqhewbuby.now.sh - добавил респонсив

2017-07-20 09:33 UTC, evgenyrodionov commented
Сделай адаптив без ресайз эвента

2017-07-20 09:33 UTC, evgenyrodionov commented
Тут чистый цсс справится

2017-07-20 09:33 UTC, evgenyrodionov commented
Но неплохо да

2017-07-24 19:51 UTC, shnider commented
https://build-iydvygsntu.now.sh

2017-07-24 23:02 UTC, imevro requested changes

2017-07-24 23:02 UTC, evgenyrodionov commented on src/App.css
> +.modal-gallery {
модал галлери что

2017-07-24 23:02 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
>  const Contetnt = styled.div`
Contetnt?

2017-07-24 23:02 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +  getTransform(index: number): Object {
почитай пр Игоря

2017-07-24 23:02 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +            <ImageInfo>Главнй фасад {this.state.active + 1}/{images.length}</ImageInfo>
Главнй фсд

2017-07-25 20:40 UTC, imevro requested changes

2017-07-25 20:40 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +function getTransform(index: number, active: number): Object {
как-то тут всё не очень очевидно. Распиши всю функцию на константы, добавь комментариев

2017-07-25 20:40 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +  const space = window.innerWidth < 992 ? -1 : 1;
вот это что значит, например? я хз

2017-07-25 20:40 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +      transform: `translate(calc(50vw - 50% + ${offset}%))`,
50vw? это что за меджик намбер?

2017-07-26 08:16 UTC, evgenyrodionov commented
Антон, а где проверять

2017-07-26 16:03 UTC, shnider commented
https://build-nyxwoeffmx.now.sh/

2017-07-27 11:25 UTC, evgenyrodionov commented
Можешь переключиться на джкьюшный апи?

2017-10-03 20:19 UTC, merged