Feat/Add adaptive complexes
shnider/yard-frontend pull request #13
Opened 2017-07-21 21:15 UTC by shnider

https://build-rqebndsyvg.now.sh
Адаптив карусели пока в процессе - чертовы картинки не желают постоянного эспект ратио

2017-07-21 21:31 UTC, evgenyrodionov commented
А куда текст уехал 

![image](https://user-images.githubusercontent.com/775692/28483281-219adb46-6e75-11e7-9c9b-74888ca9ffe8.png)

2017-07-21 21:32 UTC, imevro requested changes
https://github.com/nikolaevigor/yard-frontend/pull/29#pullrequestreview-51589794

2017-07-22 14:25 UTC, shnider commented
https://build-sppjbfbfgv.now.sh/

2017-07-22 18:06 UTC, imevro requested changes

2017-07-22 18:06 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +  @media (max-width: 990px) {
почему через max-width раз, что за нестандаратный брейкпоинт два, почему не через хелпер три

2017-07-22 18:06 UTC, evgenyrodionov commented on src/utilities.js
> +  large: (...args: any) => css`
tablet
desktop
LARGE

2017-07-24 22:38 UTC, imevro approved these changes

2017-07-24 22:38 UTC, merged