feat/deploy app on now.sh: https://build-ggshjdhfbd.now.sh/
shnider/yard-frontend pull request #6
Opened 2017-06-26 17:24 UTC by shnider

2017-06-26 19:51 UTC, shnider commented
Прошелся свежим взглядом, нашел пару косяков по отступам - поправил.
В люди же выходим.
now.sh - https://yardfront-lipmnwxzsv.now.sh/

2017-06-26 21:38 UTC, imevro requested changes

2017-06-26 21:38 UTC, evgenyrodionov commented on .directory
> +[Dolphin]
это что

2017-06-26 21:38 UTC, evgenyrodionov commented on package.json
> +    "now": "^7.1.0",
а зачем это тут

2017-06-26 21:38 UTC, evgenyrodionov commented on package.json
> +    "prepush": "node_modules/.bin/eslint src/ --ext .jsx --ext .js"
node_modules... это неправильно, достаточно `eslint src`

2017-06-26 21:38 UTC, evgenyrodionov commented on registerServiceWorker.js
> +/* eslint-disable */
поч у тебя два сервисворкера

2017-06-27 09:22 UTC, imevro requested changes
Зачем ты сервисворкер грохнул?

2017-06-27 09:39 UTC, merged