Feat/Add flow types
shnider/yard-frontend pull request #9
Opened 2017-07-01 20:30 UTC by shnider

2017-07-01 21:18 UTC, imevro requested changes

2017-07-01 21:18 UTC, evgenyrodionov commented on package.json
> +    "babel-eslint": "7",
не понял формата

в девдепс бтв, как и флоу тайпед

2017-07-01 21:18 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +  margin-bottom: 6rem;complexTypes
wtf

2017-07-01 21:18 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +function formatLocation(location): string {
локейшен-то разверни по типам

2017-07-01 21:18 UTC, evgenyrodionov commented on src/Complexes/types.js
> +export type ComplexTypes = {
поч во множ числе

2017-07-02 11:05 UTC, imevro requested changes

2017-07-02 11:05 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +                  imgAlt="CardImage"
так себе альт

2017-07-02 11:05 UTC, evgenyrodionov commented on src/api.js
> +export function get(relativePath: string): Promise<any> {
relativePath → resource

2017-07-02 11:05 UTC, evgenyrodionov commented on src/utilities.js
> +export function getImageURL(image: Object, size: number = 512): string {
имейдж распиши

2017-07-04 21:38 UTC, imevro requested changes

2017-07-04 21:38 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +                  imgAlt="ComplexImage"
да бля

2017-07-04 21:38 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +                  imgAlt="ComplexImage"
альт нужен чтобы изображение в поиске читалось

2017-07-04 21:38 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +                  imgAlt="ComplexImage"
ФОТОГРАФИЯ ЖК ПОЛЯНКА/44 лучше будет чем это

2017-07-04 21:38 UTC, evgenyrodionov commented on src/Complexes/Show/ImageSlider.jsx
> +type Props = { images: ImageType };
зачем убрал эррэй?

2017-07-04 21:38 UTC, evgenyrodionov commented on src/utilities.js
>  /* eslint-disable import/prefer-default-export*/
можно убрать уже

2017-07-05 15:48 UTC, shnider commented on src/Complexes/Show/ImageSlider.jsx
> +type Props = { images: ImageType };
эррэй в тайпс  - иначе флоу ругается, утверждает, что имеджс - обьект, не массив

2017-07-05 17:49 UTC, evgenyrodionov commented
Зачем вешать на меня ревью если билд фейлится

2017-07-05 20:35 UTC, shnider commented
эта ветка без тревис конфига

2017-07-05 21:21 UTC, imevro requested changes

2017-07-05 21:21 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +                  imgAlt={`ФОТОГРАФИЯ-${complex.name}`}
ЧТО ЗА АД-?

2017-07-05 21:21 UTC, evgenyrodionov commented on src/Complexes/types.js
> +export type ImageType = Array<{
нет, не надо в массив тут засовывать

2017-07-05 21:21 UTC, evgenyrodionov commented on src/Complexes/types.js
> +  isPublic?: boolean,
обязательно поле вроде

2017-07-05 21:21 UTC, evgenyrodionov commented on src/Complexes/types.js
> +  house?: number,
это строка вроде

2017-07-06 17:02 UTC, imevro requested changes

2017-07-06 17:02 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +                  imgAlt={`фото ${complex.name}`}
Уныло

2017-07-06 17:02 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +                  imgAlt={`фото ${complex.name}`}
Напиши просто Фотография ЖК Полянка/44

2017-07-06 23:45 UTC, imevro requested changes

2017-07-06 23:45 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    get('/api/v1/complexes').then(({ items }) => {
а зачем убрал фильтр стейт паблик

2017-07-07 05:11 UTC, shnider commented on src/Complexes/List/index.jsx
> +    get('/api/v1/complexes').then(({ items }) => {
блииин, не уследил
с апи новым разбирался, не должны были эти изменения в коммит попасть

2017-07-07 10:57 UTC, imevro requested changes

2017-07-07 10:57 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    get('/v1/complexes?filter[state]=public').then(({ items }) => {
как думаешь, оно заработает?

2017-07-07 10:57 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    get('/v1/complexes?filter[state]=public').then(({ items }) => {
если да — сделай билд на наусш, проверим

2017-07-07 16:36 UTC, shnider commented on src/Complexes/List/index.jsx
> +    get('/v1/complexes?filter[state]=public').then(({ items }) => {
Вот, все работает https://yard-shinder.now.sh/ 
Только тут _старый апи_, новый в другой ветке же - work in progress

2017-07-07 16:53 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    get('/v1/complexes?filter[state]=public').then(({ items }) => {
так меня новый интересует

2017-07-07 17:01 UTC, merged